/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=/dev/null --include-runtime=false --strict-vars=false` (hash: d40fa0a83f598479cba573e18911dad2)
interface __BaseEnv_Env {
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	NEXT_PUBLIC_POSTHOG_HOST: string;
	NEXT_PUBLIC_POSTHOG_PROJECT_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEXT_PUBLIC_POSTHOG_HOST" | "NEXT_PUBLIC_POSTHOG_PROJECT_TOKEN">> {}
}
