import { Obsid } from "obsid/react";
import { getVaultRouteManifest, vault } from "@/lib/vault/index.ts";
import schema from "@/lib/vault/schema.tsx";

interface PageProps {
  readonly params: Promise<{
    readonly path?: string[];
  }>;
}

const dynamicParams = false;

const generateStaticParams = async () => {
  const manifest = await getVaultRouteManifest();

  return manifest.routes.map((route) => ({
    path: route.segments,
  }));
};

const Page = async ({ params }: PageProps) => {
  const manifest = await getVaultRouteManifest();
  const route = manifest.getBySegments((await params).path);

  if (!route) {
    throw new Error("Received a path that was not generated by generateStaticParams");
  }

  const note = await vault.getFile(route.sourcePath);

  if (!note) {
    throw new Error(`Generated vault note is missing: ${route.sourcePath}.md`);
  }

  return <Obsid note={note} schema={schema} />;
};

// biome-ignore lint/style/useComponentExportOnlyModules: App Router pages must export route configuration beside the component.
export { dynamicParams, generateStaticParams };
export default Page;
