import { format } from "date-fns/fp";
import { ObsidianMarkdown } from "obsid/react";
import type { VaultFile, VaultLink } from "obsid/vault";
import { getVaultRouteManifest, vault } from "@/lib/vault";
import type { VaultRouteManifest } from "@/lib/vault/routing";

interface PageProps {
  readonly params: Promise<{
    readonly path?: string[];
  }>;
}

interface LinkListProps {
  readonly files: readonly VaultFile[];
  readonly getHref: VaultRouteManifest["getHref"];
}

const getUnresolvedHref = (link: VaultLink): string =>
  `#unresolved-${encodeURIComponent(link.target)}`;

const getTitle = (sourcePath: string, title: unknown): string => {
  if (typeof title === "string" && title.trim()) {
    return title;
  }

  return sourcePath.slice(sourcePath.lastIndexOf("/") + 1);
};

const getDate = (date: unknown): string => {
  if (typeof date === "string") {
    return date;
  }

  return "NO_DATE";
};

const getArticleHref = (getHref: VaultRouteManifest["getHref"], link: VaultLink): string => {
  if (!link.resolvedPath) {
    return getUnresolvedHref(link);
  }

  return getHref(link.resolvedPath) ?? getUnreesolvedHref(link);
};

const getFolderPath = (sourcePath: string): string => {
  const separatorIndex = sourcePath.lastIndexOf("/");

  if (separatorIndex === -1) {
    return "";
  }

  return sourcePath.slice(0, separatorIndex);
};

const LinkList = ({ files, getHref }: LinkListProps) => (
  <ul className="flex flex-col items-start gap-0 w-full">
    {files
      .slice()
      .sort((a, b) => new Date(b.frontmatter.date) - new Date(a.frontmatter.date))
      .map((file) => {
        const href = getHref(file.path);

        if (!href) {
          throw new Error(`Vault file is missing from the route manifest: ${file.path}.md`);
        }

        return (
          <li className="w-full" key={file.path}>
            <a className="flex justify-between items-center w-full group pb-4" href={href}>
              <span className="group-hover:underline underline-offset-2 decoration-1">
                {getTitle(file.path, file.frontmatter.title)}
              </span>
              <div className="w-full flex-1 border-b-1 -mt-2 border-neutral-100 group-hover:border-neutral-800">
                <span className="no-underline hover:no-underline">&nbsp;</span>
              </div>
              <span className="group-hover:bg-black group-hover:text-white bg-neutral-200 border-neutral-200 px-2 pt-0.5 flex justify-end -mt-2.5 border-b group-hover:border-black">
                <span>{format("do LLL y", new Date(getDate(file.frontmatter.date)))}</span>
              </span>
            </a>
          </li>
        );
      })}
  </ul>
);

const dynamicParams = false;

const generateStaticParams = async () => {
  const manifest = await getVaultRouteManifest();

  return manifest.routes.map((route) => ({
    path: route.segments,
  }));
};

const Page = async ({ params }: PageProps) => {
  const manifest = await getVaultRouteManifest();
  const route = manifest.getBySegments((await params).path);

  if (!route) {
    throw new Error("Received a path that was not generated by generateStaticParams");
  }

  const file = await vault.getFile(route.sourcePath);

  if (!file) {
    throw new Error(`Generated vault file is missing: ${route.sourcePath}.md`);
  }

  const title = getTitle(file.path, file.frontmatter.title);
  const resolveWikiLink = (link: VaultLink) => getArticleHref(manifest.getHref, link);

  const displayAsLinkList = file.frontmatter.display_as === "link-list";
  let linkListFiles: readonly VaultFile[] = [];

  if (displayAsLinkList) {
    linkListFiles = (await vault.getFolder(getFolderPath(file.path))).filter(
      (folderFile) => folderFile.path !== file.path,
    );
  }

  return (
    <div className="w-full">
      <article className="flex flex-col size-full gap-8 items-start">
        {title !== "page" && (
          <h1 className="w-full text-2xl font-semibold tracking-tight">{title}</h1>
        )}
        <div className="flex flex-col items-start gap-4 leading-normal text-neutral-800 w-full">
          <ObsidianMarkdown file={file} resolveWikiLink={resolveWikiLink} />
          {displayAsLinkList && <LinkList files={linkListFiles} getHref={manifest.getHref} />}
        </div>
      </article>
    </div>
  );
};

// biome-ignore lint/style/useComponentExportOnlyModules: App Router pages must export route configuration beside the component.
export { dynamicParams, generateStaticParams };
export default Page;
