import { ObsidianMarkdown } from "obsid/react";
import type { VaultLink } from "obsid/vault";
import { getVaultRouteManifest, vault } from "../vault.ts";
import type { VaultRouteManifest } from "../vault-routing.ts";

interface PageProps {
  readonly params: Promise<{
    readonly path?: string[];
  }>;
}

interface ResolvedLinkProps {
  readonly getHref: VaultRouteManifest["getHref"];
  readonly link: VaultLink;
}

const getUnresolvedHref = (link: VaultLink): string =>
  `#unresolved-${encodeURIComponent(link.target)}`;

const getTitle = (sourcePath: string, title: unknown): string => {
  if (typeof title === "string" && title.trim()) {
    return title;
  }

  return sourcePath.slice(sourcePath.lastIndexOf("/") + 1);
};

const getArticleHref = (getHref: VaultRouteManifest["getHref"], link: VaultLink): string => {
  if (!link.resolvedPath) {
    return getUnresolvedHref(link);
  }

  return getHref(link.resolvedPath) ?? getUnresolvedHref(link);
};

const ResolvedLink = ({ getHref, link }: ResolvedLinkProps) => {
  if (!link.resolvedPath) {
    return (
      <li className="rounded-xl border border-amber-300 bg-amber-50 p-3 text-amber-950">
        <strong>{link.label}</strong>
        <span className="ml-2 text-sm">Unresolved</span>
      </li>
    );
  }

  return (
    <li className="rounded-xl border border-emerald-200 bg-emerald-50 p-3">
      <a className="font-medium text-emerald-950 underline" href={getArticleHref(getHref, link)}>
        {link.label}
      </a>
      <code className="mt-1 block text-xs text-emerald-800">{link.resolvedPath}</code>
    </li>
  );
};

const dynamicParams = false;

const generateStaticParams = async () => {
  const manifest = await getVaultRouteManifest();

  return manifest.routes.map((route) => ({
    path: route.segments,
  }));
};

const Page = async ({ params }: PageProps) => {
  const manifest = await getVaultRouteManifest();
  const route = manifest.getBySegments((await params).path);

  if (!route) {
    throw new Error("Received a path that was not generated by generateStaticParams");
  }

  const file = await vault.getFile(route.sourcePath);

  if (!file) {
    throw new Error(`Generated vault file is missing: ${route.sourcePath}.md`);
  }

  const title = getTitle(file.path, file.frontmatter.title);
  const resolveWikiLink = (link: VaultLink) => getArticleHref(manifest.getHref, link);

  return (
    <div className="mx-auto grid min-h-screen max-w-6xl gap-10 p-6 md:grid-cols-[minmax(0,1fr)_22rem]">
      <article>
        <p className="font-mono text-xs text-neutral-500">{file.path}.md</p>
        <h1 className="mt-2 text-4xl font-semibold tracking-tight">{title}</h1>
        <div className="mt-8 text-lg leading-8 text-neutral-800">
          <ObsidianMarkdown file={file} resolveWikiLink={resolveWikiLink} />
        </div>
      </article>

      <aside className="space-y-8 rounded-3xl bg-neutral-950 p-6 text-neutral-100 md:sticky md:top-8 md:self-start">
        <section>
          <h2 className="text-sm font-semibold uppercase tracking-wider text-neutral-400">
            Frontmatter
          </h2>
          <pre className="mt-3 overflow-x-auto text-sm text-neutral-200">
            {JSON.stringify(file.frontmatter, null, 2)}
          </pre>
        </section>

        <section>
          <h2 className="text-sm font-semibold uppercase tracking-wider text-neutral-400">
            Article links
          </h2>
          <ul className="mt-3 space-y-2 text-neutral-950">
            {file.links.map((link) => (
              <ResolvedLink getHref={manifest.getHref} key={link.target} link={link} />
            ))}
          </ul>
        </section>
      </aside>
    </div>
  );
};

// biome-ignore lint/style/useComponentExportOnlyModules: App Router pages must export route configuration beside the component.
export { dynamicParams, generateStaticParams };
export default Page;
